# Generated by Django 5.2.6 on 2025-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltower',
            name='photo',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltower',
            name='photo_height',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltower',
            name='photo_width',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', upload_to='eda/tower/photo', width_field='photo_width'),
        ),
        migrations.AddField(
            model_name='tower',
            name='photo_height',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='photo_width',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
