# Generated by Django 5.2.8 on 2025-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', 'forename', 'tower', 'email', 'phone1', 'phone2']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Personal or role email address', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, help_text="Person's surname, or role title", max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, help_text='Phone number', max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=False, help_text='Primary contact for this Tower?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='publish',
            field=models.BooleanField(default=True, help_text='Publish these details (in the Annual Report, on the web, etc.)'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Personal or role email address', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(blank=True, help_text="Person's surname, or role title", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone1',
            field=models.CharField(blank=True, help_text='Phone number', max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone2',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='primary',
            field=models.BooleanField(default=False, help_text='Primary contact for this Tower?'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='publish',
            field=models.BooleanField(default=True, help_text='Publish these details (in the Annual Report, on the web, etc.)'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('phone1', ''), _negated=True), models.Q(('phone2', ''), _negated=True), models.Q(('email', ''), _negated=True), models.Q(('form', ''), _negated=True), _connector='OR'), name='no_non_blank_contact_persons', violation_error_message="Contact details can't be entirely blank"),
        ),
    ]
