# Generated by Django 5.2.8 on 2025-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0002_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='contact',
            name='no_non_blank_contact_persons',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('phone1', ''), _negated=True), models.Q(('phone2', ''), _negated=True), models.Q(('email', ''), _negated=True), models.Q(('form', ''), _negated=True), _connector='OR'), name='no_non_blank_contact_persons', violation_error_message='Need at least one of name, phone, email or form'),
        ),
    ]
