# Generated by Django 5.2.6 on 2025-09-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0002_historicaltower_photo_historicaltower_photo_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='historicaltower',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='historicaltower',
            name='photo_width',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='photo_width',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, height_field='photo_height', upload_to='eda/tower/photo', width_field='photo_width')),
                ('photo_height', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('photo_width', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower_database.tower')),
            ],
            options={
                'ordering': ['tower__place', 'tower__dedication'],
            },
        ),
    ]
