# Generated by Django 5.2.8 on 2025-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0003_alter_contact_no_non_blank_contact_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphoto',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Short text description of the photo', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Short text description of the photo', max_length=50),
        ),
    ]
