# Generated by Django 5.2.6 on 2025-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0003_remove_historicaltower_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['tower']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', upload_to='tower_database/photo/photo', width_field='photo_width'),
        ),
    ]
