# Generated by Django 5.2.8 on 2025-12-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0004_historicalphoto_alt_text_photo_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphoto',
            name='credit',
            field=models.CharField(blank=True, help_text='Source of the photo', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, help_text='Source of the photo', max_length=100),
        ),
    ]
