# Generated by Django 5.2.6 on 2025-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0004_alter_photo_options_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='no_non_blank_contacts',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='form',
            field=models.URLField(blank=True, help_text='Link to a contact form'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='form',
            field=models.URLField(blank=True, help_text='Link to a contact form'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name', 'phone', 'phone2', 'email', 'form')},
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('phone', ''), _negated=True), models.Q(('phone2', ''), _negated=True), models.Q(('email', ''), _negated=True), models.Q(('form', ''), _negated=True), _connector='OR'), name='no_non_blank_contacts', violation_error_message="Contacts can't be entirely blank"),
        ),
    ]
