# Generated by Django 5.2.6 on 2025-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0005_remove_contact_no_non_blank_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltower',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tower',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
