# Generated by Django 5.2.7 on 2025-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0008_alter_historicaltower_practice_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltower',
            name='practice_day',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], help_text='Day of the week of main practice', max_length=9),
        ),
        migrations.AlterField(
            model_name='tower',
            name='practice_day',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], help_text='Day of the week of main practice', max_length=9),
        ),
    ]
