# Generated by Django 5.2.7 on 2025-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0009_alter_historicaltower_practice_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmap',
            name='role',
            field=models.CharField(choices=[('C', 'Other Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontactmap',
            name='role',
            field=models.CharField(choices=[('C', 'Other Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
    ]
