# Generated by Django 5.2.7 on 2025-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0010_alter_contactmap_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltower',
            old_name='contact_use',
            new_name='contact_restriction',
        ),
        migrations.RenameField(
            model_name='tower',
            old_name='contact_use',
            new_name='contact_restriction',
        ),
    ]
