# Generated by Django 5.2.7 on 2025-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0011_rename_contact_use_historicaltower_contact_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltower',
            name='contact_restriction',
            field=models.CharField(choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], default='NONE', help_text='Intended use of contact details', max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='contact_restriction',
            field=models.CharField(choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], default='NONE', help_text='Intended use of contact details', max_length=10),
        ),
    ]
