# Generated by Django 5.2.7 on 2025-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0012_alter_historicaltower_contact_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmap',
            name='role',
            field=models.CharField(choices=[('C', 'Other General Contact'), ('BL', 'Other Bells Contact'), ('BA', 'Other Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontactmap',
            name='role',
            field=models.CharField(choices=[('C', 'Other General Contact'), ('BL', 'Other Bells Contact'), ('BA', 'Other Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
    ]
