# Generated by Django 5.2.7 on 2025-11-12 12:49

import multiselectfield.db.fields
import tower_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0013_alter_contactmap_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltower',
            name='contact_restriction',
            field=models.CharField(blank=True, choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], help_text='Intended use of contact details', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaltower',
            name='practice_weeks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('not', 'Not'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('alternate', 'Alternate')], help_text='Week(s) of the month for main practice if not all', max_length=50, validators=[tower_database.models.Tower.week_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='contact_restriction',
            field=models.CharField(blank=True, choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], help_text='Intended use of contact details', max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='practice_weeks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('not', 'Not'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('alternate', 'Alternate')], help_text='Week(s) of the month for main practice if not all', max_length=50, validators=[tower_database.models.Tower.week_validator]),
        ),
    ]
