# Generated by Django 5.2.7 on 2025-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0014_alter_historicaltower_contact_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text="Contact email address (not necessirally the individual's)", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(blank=True, help_text="Contact email address (not necessirally the individual's)", max_length=100),
        ),
    ]
