# Generated by Django 5.2.7 on 2025-11-16 17:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0015_alter_contact_email_alter_historicalcontact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Person's title (if required - usually leave blank)", max_length=5)),
                ('forename', models.CharField(blank=True, help_text="Person's forename", max_length=100)),
                ('name', models.CharField(help_text="Person's surname, or office title", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('phone2', models.CharField(blank=True, help_text='Alternate phone number', max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Contact email address for person or office', max_length=100)),
            ],
            options={
                'ordering': ['name', 'forename', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContactPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Person's title (if required - usually leave blank)", max_length=5)),
                ('forename', models.CharField(blank=True, help_text="Person's forename", max_length=100)),
                ('name', models.CharField(help_text="Person's surname, or office title", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=100)),
                ('phone2', models.CharField(blank=True, help_text='Alternate phone number', max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Contact email address for person or office', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical contact person',
                'verbose_name_plural': 'historical contact persons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='contactmap',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactmap',
            name='tower',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='other_contacts',
        ),
        migrations.RemoveField(
            model_name='historicalcontactmap',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalcontactmap',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcontactmap',
            name='tower',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['tower', 'person__name', 'person__forename', 'person__title']},
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='no_non_blank_contacts',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='phone2',
        ),
        migrations.AddField(
            model_name='contact',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('C', 'Other General Contact'), ('BL', 'Other Bells Contact'), ('BA', 'Other Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='tower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tower_database.tower'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('C', 'Other General Contact'), ('BL', 'Other Bells Contact'), ('BA', 'Other Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='tower',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tower_database.tower'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=100),
        ),
        migrations.AlterField(
            model_name='tower',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conatct_primary_set', to='tower_database.contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together={('forename', 'name', 'phone', 'phone2', 'email')},
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tower_database.contactperson'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tower_database.contactperson'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContactMap',
        ),
        migrations.DeleteModel(
            name='HistoricalContactMap',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone2',
        ),
    ]
