# Generated by Django 5.2.7 on 2025-11-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0015_alter_contact_email_alter_historicalcontact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication'], 'permissions': [('change_cambridge', 'can change Cambridge towers'), ('ely', 'can change Ely towers'), ('change_huntingdon', 'can change Huntingdon towers'), ('change_wisbech', 'can change Wisbech towers')]},
        ),
    ]
