# Generated by Django 5.2.7 on 2025-11-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0016_alter_tower_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication'], 'permissions': [('change_cambridge', 'Can change Cambridge towers'), ('ely', 'Can change Ely towers'), ('change_huntingdon', 'Can change Huntingdon towers'), ('change_wisbech', 'Can change Wisbech towers')]},
        ),
    ]
