# Generated by Django 5.2.7 on 2025-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0017_historicalphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.'), ('Dr', 'Dr.'), ('Rev', "The Rev'd")], help_text="Person's title (if required - usually leave blank)", max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.'), ('Dr', 'Dr.'), ('Rev', "The Rev'd")], help_text="Person's title (if required - usually leave blank)", max_length=5),
        ),
    ]
