# Generated by Django 5.2.7 on 2025-11-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0017_alter_tower_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication'], 'permissions': [('change_c', 'Can change Cambridge towers'), ('change_e', 'Can change Ely towers'), ('change_h', 'Can change Huntingdon towers'), ('change_w', 'Can change Wisbech towers')]},
        ),
    ]
