# Generated by Django 5.2.7 on 2025-11-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0018_alter_tower_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication'], 'permissions': [('change_c_tower', 'Can change Cambridge towers'), ('change_e_tower', 'Can change Ely towers'), ('change_h_tower', 'Can change Huntingdon towers'), ('change_w_tower', 'Can change Wisbech towers')]},
        ),
    ]
