# Generated by Django 5.2.7 on 2025-11-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0019_alter_contact_role_alter_historicalcontact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('C', 'General Contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('C', 'General Contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
    ]
