# Generated by Django 5.2.7 on 2025-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0019_alter_tower_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dove',
            fields=[
                ('towerid', models.CharField(blank=True, db_column='TowerID', null=True)),
                ('ringid', models.CharField(db_column='RingID', primary_key=True, serialize=False)),
                ('ringtype', models.CharField(blank=True, db_column='RingType', null=True)),
                ('place', models.CharField(blank=True, db_column='Place', null=True)),
                ('place2', models.CharField(blank=True, db_column='Place2', null=True)),
                ('placecl', models.CharField(blank=True, db_column='PlaceCL', null=True)),
                ('dedicn', models.CharField(blank=True, db_column='Dedicn', null=True)),
                ('towerstatus', models.CharField(blank=True, db_column='TowerStatus', null=True)),
                ('statusfirst', models.CharField(blank=True, db_column='StatusFirst', null=True)),
                ('barededicn', models.CharField(blank=True, db_column='BareDedicn', null=True)),
                ('altname', models.CharField(blank=True, db_column='AltName', null=True)),
                ('ringname', models.CharField(blank=True, db_column='RingName', null=True)),
                ('region', models.CharField(blank=True, db_column='Region', null=True)),
                ('county', models.CharField(blank=True, db_column='County', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', null=True)),
                ('histregion', models.CharField(blank=True, db_column='HistRegion', null=True)),
                ('iso3166code', models.CharField(blank=True, db_column='ISO3166code', null=True)),
                ('diocese', models.CharField(blank=True, db_column='Diocese', null=True)),
                ('lat', models.CharField(blank=True, db_column='Lat', null=True)),
                ('long', models.CharField(blank=True, db_column='Long', null=True)),
                ('bells', models.CharField(blank=True, db_column='Bells', null=True)),
                ('ur', models.CharField(blank=True, db_column='UR', null=True)),
                ('semitones', models.CharField(blank=True, db_column='Semitones', null=True)),
                ('wt', models.CharField(blank=True, db_column='Wt', null=True)),
                ('app', models.CharField(blank=True, db_column='App', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', null=True)),
                ('hz', models.CharField(blank=True, db_column='Hz', null=True)),
                ('details', models.CharField(blank=True, db_column='Details', null=True)),
                ('gf', models.CharField(blank=True, db_column='GF', null=True)),
                ('toilet', models.CharField(blank=True, db_column='Toilet', null=True)),
                ('simulator', models.CharField(blank=True, db_column='Simulator', null=True)),
                ('extrainfo', models.CharField(blank=True, db_column='ExtraInfo', null=True)),
                ('webpage', models.CharField(blank=True, db_column='WebPage', null=True)),
                ('affiliations', models.CharField(blank=True, db_column='Affiliations', null=True)),
                ('ng', models.CharField(blank=True, db_column='NG', null=True)),
                ('postcode', models.CharField(blank=True, db_column='Postcode', null=True)),
                ('practice', models.CharField(blank=True, db_column='Practice', null=True)),
                ('ovhaulyr', models.CharField(blank=True, db_column='OvhaulYr', null=True)),
                ('contractor', models.CharField(blank=True, db_column='Contractor', null=True)),
                ('tuneyr', models.CharField(blank=True, db_column='TuneYr', null=True)),
                ('lgrade', models.CharField(blank=True, db_column='LGrade', null=True)),
                ('bldgid', models.CharField(blank=True, db_column='BldgID', null=True)),
                ('churchcare', models.CharField(blank=True, db_column='ChurchCare', null=True)),
                ('chrassetid', models.CharField(blank=True, db_column='CHRAssetID', null=True)),
                ('towerbase', models.CharField(blank=True, db_column='TowerBase', null=True)),
                ('doveid', models.CharField(blank=True, db_column='DoveID', null=True)),
                ('snlat', models.CharField(blank=True, db_column='SNLat', null=True)),
                ('snlong', models.CharField(blank=True, db_column='SNLong', null=True)),
            ],
            options={
                'db_table': 'dove_towers',
                'ordering': ['place', 'dedicn'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DoveTower',
        ),
    ]
