# Generated by Django 5.2.7 on 2025-11-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0020_dove_delete_dovetower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication'], 'permissions': [('admin_cambridge', 'Can admin Cambridge towers'), ('admin_ely', 'Can admin Ely towers'), ('admin_huntingdon', 'Can admin Huntingdon towers'), ('admin_wisbech', 'Can admin Wisbech towers')]},
        ),
    ]
