# Generated by Django 5.2.7 on 2025-11-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0020_alter_contact_role_alter_historicalcontact_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='primary_contact',
        ),
    ]
