# Generated by Django 5.2.7 on 2025-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0021_remove_historicaltower_primary_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='contact_restriction',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='contact_restriction',
        ),
        migrations.AddField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=False, help_text='Primary com=ntact for this Tower?'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='primary',
            field=models.BooleanField(default=False, help_text='Primary com=ntact for this Tower?'),
        ),
        migrations.AddField(
            model_name='historicaltower',
            name='primary_contact_restriction',
            field=models.CharField(blank=True, choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], help_text='Intended use of primary contact details', max_length=10),
        ),
        migrations.AddField(
            model_name='tower',
            name='primary_contact_restriction',
            field=models.CharField(blank=True, choices=[('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], help_text='Intended use of primary contact details', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('C', 'Contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('C', 'Contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together={('title', 'forename', 'name')},
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('tower',), name='unique_tower_primary', violation_error_message='Towers can only have a single primary contact'),
        ),
    ]
