# Generated by Django 5.2.7 on 2025-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0022_remove_historicaltower_contact_restriction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['name', 'forename', 'title'], 'verbose_name_plural': 'Contact People'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontactperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact person', 'verbose_name_plural': 'historical Contact People'},
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='historicalcontactperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalcontactperson',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontactperson',
            name='phone2',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal/office email address', max_length=100),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='personal_phone',
            field=models.CharField(blank=True, help_text='Personal/office contact phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='personal_phone2',
            field=models.CharField(blank=True, help_text='Alternate personal/office phone number', max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal/office email address', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='personal_phone',
            field=models.CharField(blank=True, help_text='Personal/office contact phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='personal_phone2',
            field=models.CharField(blank=True, help_text='Alternate personal/office phone number', max_length=100, verbose_name='Phone'),
        ),
    ]
