# Generated by Django 5.2.7 on 2025-11-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0023_alter_contactperson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='primary_contact_restriction',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='primary_contact_restriction',
        ),
    ]
