# Generated by Django 5.2.7 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0024_remove_historicaltower_primary_contact_restriction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(blank=True, help_text="Person's surname, or office title", max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='name',
            field=models.CharField(blank=True, help_text="Person's surname, or office title", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together={('title', 'forename', 'name', 'personal_phone', 'personal_email')},
        ),
    ]
