# Generated by Django 5.2.7 on 2025-11-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0021_alter_tower_options'),
        ('tower_database', '0025_alter_contactperson_unique_together_and_more'),
    ]

    operations = [
    ]
