# Generated by Django 5.2.7 on 2025-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0026_merge_20251119_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['name', 'forename', 'title'], 'permissions': [('admin_cambridge', 'Can admin Cambridge towers'), ('admin_ely', 'Can admin Ely towers'), ('admin_huntingdon', 'Can admin Huntingdon towers'), ('admin_wisbech', 'Can admin Wisbech towers')], 'verbose_name_plural': 'Contact People'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['tower', 'photo_height']},
        ),
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['place', 'dedication']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['tower', 'website']},
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalwebsite',
            name='link_text',
            field=models.CharField(blank=True, help_text='Short link text for this website', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='link_text',
            field=models.CharField(blank=True, help_text='Short link text for this website', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('C', 'General contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='personal_phone2',
            field=models.CharField(blank=True, help_text='Alternate personal/office phone number', max_length=100, verbose_name='Other personal phone'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.'), ('Dr', 'Dr.'), ('Revd', "The Rev'd")], help_text="Person's title (if required - usually leave blank)", max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('C', 'General contact'), ('BL', 'Bells Contact'), ('BA', 'Band Contact'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='personal_phone2',
            field=models.CharField(blank=True, help_text='Alternate personal/office phone number', max_length=100, verbose_name='Other personal phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.'), ('Dr', 'Dr.'), ('Revd', "The Rev'd")], help_text="Person's title (if required - usually leave blank)", max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together={('title', 'forename', 'name', 'personal_phone', 'personal_phone2', 'personal_email')},
        ),
        migrations.AddConstraint(
            model_name='contactperson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('personal_phone', ''), _negated=True), models.Q(('personal_phone2', ''), _negated=True), models.Q(('personal_email', ''), _negated=True), _connector='OR'), name='no_non_blank_contact_persons', violation_error_message="Contact Person details can't be entirely blank"),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('tower', 'website'), name='unique_tower_website', violation_error_message="Can't have the same website more than once for the same tower"),
        ),
    ]
