# Generated by Django 5.2.7 on 2025-11-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0027_alter_contactperson_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['name', 'forename', 'title'], 'verbose_name_plural': 'Contact People'},
        ),
    ]
