# Generated by Django 5.2.8 on 2025-11-23 19:34

import tower_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0028_alter_contactperson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', upload_to=tower_database.models.rename_image, width_field='photo_width'),
        ),
    ]
