# Generated by Django 5.2.8 on 2025-11-24 13:19

import tower_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0029_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphoto',
            name='photo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to=tower_database.models.rename_image, width_field='photo_width'),
        ),
    ]
