# Generated by Django 5.2.8 on 2025-11-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0030_alter_historicalphoto_photo_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dove',
            options={'managed': False, 'ordering': ['place', 'dedicn'], 'verbose_name': 'dove record'},
        ),
    ]
