# Generated by Django 5.2.8 on 2025-11-24 13:42

import tower_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0031_alter_dove_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['tower', 'height']},
        ),
        migrations.RenameField(
            model_name='historicalphoto',
            old_name='photo_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='historicalphoto',
            old_name='photo_width',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_width',
            new_name='width',
        ),
        migrations.AddField(
            model_name='historicalphoto',
            name='credit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='height', upload_to=tower_database.models.rename_image, width_field='width'),
        ),
    ]
