# Generated by Django 5.2.8 on 2025-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0032_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['tower', 'url']},
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_tower_website',
        ),
        migrations.RenameField(
            model_name='historicalphoto',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='historicaltower',
            old_name='position',
            new_name='latlng',
        ),
        migrations.RenameField(
            model_name='historicalwebsite',
            old_name='website',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tower',
            old_name='position',
            new_name='latlng',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='website',
            new_name='url',
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('tower', 'url'), name='unique_tower_url', violation_error_message="Can't have the same website more than once for the same tower"),
        ),
    ]
