# Generated by Django 5.2.8 on 2025-11-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0033_alter_website_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='historicaltower',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='lng',
        ),
        migrations.AlterField(
            model_name='historicaltower',
            name='latlng',
            field=models.CharField(blank=True, max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='latlng',
            field=models.CharField(blank=True, max_length=20, verbose_name='Location'),
        ),
    ]
