# Generated by Django 5.2.8 on 2025-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0034_remove_historicaltower_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltower',
            name='os_grid',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='os_grid',
        ),
    ]
