# Generated by Django 5.2.8 on 2025-11-25 17:25

import tower_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0035_remove_historicaltower_os_grid_remove_tower_os_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltower',
            name='practice',
            field=models.CharField(blank=True, help_text='Short description of normal practice ringing. No initial capital (unless day of week)', max_length=200, validators=[tower_database.models.Tower.time_validator]),
        ),
        migrations.AlterField(
            model_name='historicaltower',
            name='service',
            field=models.CharField(blank=True, help_text='Short description of normal service ringing. No initial capital (unless day of week)', max_length=200, validators=[tower_database.models.Tower.time_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='practice',
            field=models.CharField(blank=True, help_text='Short description of normal practice ringing. No initial capital (unless day of week)', max_length=200, validators=[tower_database.models.Tower.time_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='service',
            field=models.CharField(blank=True, help_text='Short description of normal service ringing. No initial capital (unless day of week)', max_length=200, validators=[tower_database.models.Tower.time_validator]),
        ),
    ]
