# Generated by Django 5.2.8 on 2025-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_database', '0036_alter_historicaltower_practice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('C', 'General'), ('BL', 'Bells'), ('BA', 'Band'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('C', 'General'), ('BL', 'Bells'), ('BA', 'Band'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
    ]
